<!DOCTYPE html>
<html lang="{{ site.lang | default: "en-US" }}">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="chrome=1">
    <meta name="robots" content="index, follow" />
    <title>Streamiz.Kafka.Net: A .NET stream processing library for Apache Kafka (TM)</title>
    <meta name="description"
        content="Streamiz.Kafka.Net is a .NET stream processing library for Apache Kafka (TM)">
    <meta name="keywords"
        content="Streaming, Kafka, Kafka Streams" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="shortcut icon" type="image/png" href="{{ '/assets/favicon.ico'  | absolute_url }}">
    <link rel="stylesheet" href="{{ '/assets/css/style.css?v=' | append: site.github.build_revision | relative_url }}">

    {% seo %}
</head>

<body class="bg-light">
    <nav class="navbar navbar-expand-md navbar-dark fixed-left" style="background-color: #303030;">
        <a class="navbar-brand" href="https://github.com/LGouellec/kafka-streams-dotnet">Streamiz.Kafka.Net</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon bg-dark"></span>
        </button>
        <a href="https://github.com/LGouellec/kafka-streams-dotnet">
            <svg class="octicon octicon-mark-github v-align-middle" height="64" fill="#e7e7e7" viewBox="0 0 16 16"
                version="1.1" width="64" aria-hidden="true">
                <path fill-rule="evenodd"
                    d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0016 8c0-4.42-3.58-8-8-8z">
                </path>
            </svg>
        </a>
        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            {% include summary.html %}
        </div>
    </nav>

    <div class="container">
        {{ content }}
    </div>

    <footer>
        {% if site.github.is_project_page %}
        {{ site.title | default: site.github.repository_name }} is maintained by <a
            href="{{ site.github.owner_url }}">{{ site.github.owner_name }}</a><br>
        {% endif %}
        This page was generated by <a href="https://pages.github.com">GitHub Pages</a>.
    </footer>
    {% if site.google_analytics %}
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
                m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
        ga('create', '{{ site.google_analytics }}', 'auto');
        ga('send', 'pageview');
    </script>
    {% endif %}

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>

</html>