github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # configure whether Gitpod registers itself as a status check to pull requests
    addCheck: false

image:
  file: .gitpod.Dockerfile

tasks:
  - name: prebuild
    init: |
      chmod +x start.sh
      ./start.sh
      sleep 5
      mkdir -p /tmp/dotnet && curl -fsSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 6.0 --install-dir /tmp/dotnet 
      gp sync-done prebuild
  - name: restore, build and start demo stream project
    init: gp sync-await prebuild
    command: |
      dotnet dev-certs https
      dotnet restore
      dotnet build -f net6.0 --no-restore
      dotnet run -f net6.0 --project samples/sample-stream-demo/sample-stream-demo.csproj --no-build --no-restore

vscode:
  extensions:
    - muhammad-sammy.csharp

ports:
# streamiz metrics
- port: 9090
  onOpen: ignore
# zookeeper
- port: 2181
  onOpen: ignore
# broker
- port: 9092
  onOpen: ignore
- port: 9101
  onOpen: ignore
# akhq
- port: 8082
  onOpen: ignore
# schema-registry
- port: 8081
  onOpen: ignore