  version: 2.1

  orbs:
    #sonarcloud: sonarsource/sonarcloud@1.0.1
    sonarcloud-dotnet: ksmc/sonarcloud-dotnet@0.0.9

  jobs:
    build:
      docker:
        - image: mcr.microsoft.com/dotnet/core/sdk:3.1
      steps:
        - checkout
        - sonarcloud-dotnet/setup-sonar
        - run: echo "deb http://ftp.us.debian.org/debian stretch main contrib non-free" >> /etc/apt/sources.list
        - run: apt update
        - run: apt install -y unzip
        - sonarcloud-dotnet/run-scan
            project_key: kafka-streams-dotnet
            organization: LGouellec
        - run: dotnet build
        - sonarcloud-dotnet/end-scan
        #- sonarcloud/scan

  workflows:
    main:
      jobs:
        - build:
            context: SonarCloud