  version: 2.1

  orbs:
    # win: circleci/windows@2.2.0
    sonarcloud: sonarsource/sonarcloud@1.0.1

  jobs:
    build:
      docker:
        - image: mcr.microsoft.com/dotnet/core/sdk:3.1
      #executor: win/default
      steps:
        - checkout
        - run: echo "deb http://ftp.us.debian.org/debian stretch main contrib non-free" >> /etc/apt/sources.list
        - run: apt update
        - run: apt install -y unzip
        - run: dotnet build
        - sonarcloud/scan

  workflows:
    main:
      jobs:
        - build:
            context: SonarCloud