  version: 2.1

  # orbs:
  #   win: circleci/windows@2.2.0
  #   sonarcloud: sonarsource/sonarcloud@1.0.1

  jobs:
    build:
      docker:
        - image: mcr.microsoft.com/dotnet/core/sdk:3.1
      #executor: win/default
      steps:
        - checkout
        - run: dotnet build
        - sonarcloud/scan

  workflows:
    main:
      jobs:
        - build:
            context: SonarCloud